### ISSUE TITLE
Chrome WebDriver configuration

### ISSUE THREAD

**Issue by onnovalkering** [wbtstr/wbtstr#1]
It should be possible to configure all the options on the Chrome WebDriver through WbTstr. The first step is through a configuration file, preferably a custom block within the App.config. Each block should have a unique name.

When in a test fixture a configuration "preset" is provided, the corresponding configuration should be loaded while initializing the WebDriver, e.g. the following should load the _Config1_ preset from the configuration file:

`[WebDriverConfig(WebDriverType.Chrome, "Config1")]`

In case of the Chrome WebDriver the _ChromeWebDriverConfig_ class should be populated with configuration, while requested by _WbTstrFixture_ with _GetFromPreset_ from the _WebDriverConfigs_ class.

A list of all possible settings can be found on: 

https://sites.google.com/a/chromium.org/chromedriver/capabilities.

**Comment by rickvanschalkwijk** [comment]
@onnovalkering Would you mind assigning this issue to my?

**Comment by rickvanschalkwijk** [comment]
Pull request has been created. Only the build on the server is failing. It's probably because NuGet timed-out, can you restart the build? Because I don't have the rights to do so.

**Comment by onnovalkering** [comment]
The NuGet time-out is due to connectivity issues at AppVeyor. I've added the proposed fix to `appveyor.yml`. If you pull the latest commit from the `develop` branch the time-out issue should be fixed.

**Comment by rickvanschalkwijk** [comment]
@onnovalkering can we close this issue?
