### ISSUE TITLE
Change author in nuspec

### ISSUE THREAD

**Issue by onnovalkering** [wbtstr/wbtstr#6]
Can the author field in the two nuspec files be changed from 'Onno Valkering' to e.g. 'Mirabeau'?

Source/WbTstr/WbTstr.nuspec (wbtstr repo)
Source/WbTstr.Drivers.Chrome.nuspec (wbtstr-drivers-chrome repo)

Thanks!

**Comment by rickvanschalkwijk** [comment]
Changed author name in the nuspec files
